TRUNCATE dds.h_category CASCADE;
TRUNCATE dds.h_order CASCADE;
TRUNCATE dds.h_product CASCADE;
TRUNCATE dds.h_restaurant CASCADE;
TRUNCATE dds.h_user CASCADE;
TRUNCATE dds.l_order_product CASCADE;
TRUNCATE dds.l_order_user CASCADE;
TRUNCATE dds.l_product_category CASCADE;
TRUNCATE dds.l_product_restaurant CASCADE;
TRUNCATE dds.s_order_cost CASCADE;
TRUNCATE dds.s_order_status CASCADE;
TRUNCATE dds.s_product_names CASCADE;
TRUNCATE dds.s_restaurant_names CASCADE;
TRUNCATE dds.s_user_names CASCADE;
truncate stg.order_events;
truncate cdm.user_category_counters;
truncate cdm.user_product_counters;